# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://111hicksstreet15c.com
title: 111 Hicks Street, Brooklyn, NY 11201
subTitle: Asking, $535,000
email: your-email@domain.com
author: Your Name
description:
  A website showcasing the coop 111 Hicks Street 15C for sale in Brooklyn Heights, Brooklyn, New York City
copyright: 'Copyright &copy; 2020. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: hhttps://www.instagram.com/stgeorgetower/

contact_url:
  - url: http://google.com
